name: ci pipeline
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps: 
    - name: run linter
      run: npm run lint
    - name: run unit tests
      run: npm test
    - name: generate artifact
      run: npm run build
    - name: upload artifact
      uses: actions/upload-artifact
      with:
        name: build
        path: build/
